### ISSUE TITLE
通过自己服务器地址打开控制台

### ISSUE THREAD

**Issue by Extrwave** [liujiaqi7998/GrasscuttersWebDashboard#1]
目前打开控制台需要到[这个地址](https://liujiaqi7998.github.io/)才能打开对吧，
能不能集成到插件内部，不需要外链就能直接打开？支持自定义token？

**Comment by liujiaqi7998** [comment]
你可以通过修改配置文件“GWDconfig.json”来修改token
外部链接是为了方便我对前端进行优化，你可以下载docs文件夹下的代码部署在你的服务器上，但是记得定期来更新一下
