### ISSUE TITLE
SSL证书配置

### ISSUE THREAD

**Issue by ZXAS007** [liujiaqi7998/GrasscuttersWebDashboard#12]
请问一下我配置了一个SSL证书，连接的时候提示证书域名与网站域名不匹配如何解决？

**Comment by liujiaqi7998** [comment]
域名证书配置失败可能是证书格式转换错误，请互联网搜索证书相关知识并修复

**Comment by ZXAS007** [comment]
不兼容ECC加密证书？

**Comment by liujiaqi7998** [comment]
抱歉这个我不清楚，请咨询Grasscutters了解证书的原理
