### ISSUE TITLE
有的手机和电脑能连接上，有的连不上

### ISSUE THREAD

**Issue by Name-XiaoBao** [liujiaqi7998/GrasscuttersWebDashboard#15]
刚开始电脑还能连接上，后来我的电脑就连不上了，然后我用手机试了一下，发现在有些手机上可以正常连接，而有的手机或电脑也连接不上

**Comment by liujiaqi7998** [comment]
可能是Github被DNS污染了，建议清除浏览器缓存重试

**Comment by Name-XiaoBao** [comment]
可是我清除缓存后发现还是连接不上，换了好几个浏览器也不行，甚至于重装浏览器




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月18日(星期六) 凌晨0:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liujiaqi7998/GrasscuttersWebDashboard] 有的手机和电脑能连接上，有的连不上 (Issue #15)






可能是Github被DNS污染了，建议清除浏览器缓存重试

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by Name-XiaoBao** [comment]
网页的话是可以正常访问的，就是wss连接不上

**Comment by liujiaqi7998** [comment]
看说明，检测SSL问题
