### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by kuyoos** [liujiaqi7998/GrasscuttersWebDashboard#18]
如何将GrasscuttersWebDashboard.webtools所在权限节点转移到play节点上
谢谢

**Comment by kuyoos** [comment]
或者就像/help那样可以直接使用

**Comment by liujiaqi7998** [comment]
修改webtoolsPluginCommand.java 和 tpmPluginCommand.java 文件里面的permission标记可以切换节点

**Comment by liujiaqi7998** [comment]
默认节点是GrasscuttersWebDashboard.*，已收到你提出的问题会在下个版本修复

**Comment by kuyoos** [comment]
好的谢谢   我去按照你的方法试试
