### ISSUE TITLE
为什么没有权限

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [liujiaqi7998/GrasscuttersWebDashboard#23]
通过 autoCreate 自动注册的account，无法使用/wt，而使用服务器 account create 创建的用户就有权限为什么呢？

**Comment by liujiaqi7998** [comment]
权限节点：GrasscuttersWebDashboard.webtools
权限节点：GrasscuttersWebDashboard.tpm
自动注册，请修改，配置文件里的默认权限配置，将这两个权限添加在里面，否则插件是无法使用的
