### ISSUE TITLE
Android Edge Browser Cannot Connect

### ISSUE THREAD

**Issue by Extrwave** [liujiaqi7998/GrasscuttersWebDashboard#4]
方便测试一下安卓端Edge浏览器无法登陆的问题嘛？

连接失败
与服务器断开连接

并且控制台没有任何输出或者log

**Comment by Extrwave** [comment]
OPPO 自带浏览器可以登录，Edge应该为特定情况

**Comment by liujiaqi7998** [comment]
好的，我不是太擅长前端的开发，可能是手机Edge浏览器安全限制的问题，我会继续跟进修复

**Comment by Zhaokugua** [comment]
似乎是证书问题，某些浏览器不信任那个wss连接
手机上via浏览器实测是可以用的

**Comment by liujiaqi7998** [comment]
对的，是证书问题，服务器可以部署域名和SSL证书，局域网实在是没有太好的解决办法
