### ISSUE TITLE
报错 连接失败 与服务器断开连接

### ISSUE THREAD

**Issue by nizuowanzhenbang** [liujiaqi7998/GrasscuttersWebDashboard#5]
输入wss://xxx.xxx.xxx.xxx:443/Dashboard/GrasscuttersWebDashboard，一直提示 连接失败 与服务器断开连接，最新版gc jar包和wdb jar 包

**Comment by liujiaqi7998** [comment]
首先当你尝试连接时，看控制台是否出现`[WEB控制台] 用户登录到了Web控制台，ID：xxxxxx`字样
如果没出现，可以在浏览器按F12打开开发者工具检测是否有错误
大概的原因：浏览器拒绝了不安全的SSL连接
解决方案：1.关闭浏览器SSL连接校验，2.部署官签的SSL证书

**Comment by nizuowanzhenbang** [comment]
有的，显示
token:  xxxxxxx
启动完成wss://xxx.xxx.xxx.xxx:443/Dashboard/GrasscuttersWebDashboard

**Comment by liujiaqi7998** [comment]
我的意思是，当你使用浏览器连接是是否出现`[WEB控制台] 用户登录到了Web控制台，ID：xxxxxx`字样

**Comment by nizuowanzhenbang** [comment]
没有哦

**Comment by liujiaqi7998** [comment]
如果没出现，可以在浏览器按F12打开开发者工具检测是否有错误
大概的原因：浏览器拒绝了不安全的SSL连接
解决方案：1.关闭浏览器SSL连接校验，2.部署官签的SSL证书

**Comment by nizuowanzhenbang** [comment]
(index):126 WebSocket connection to 'wss://xxx.xxx.xxx.xxx/Dashboard/GrasscuttersWebDashboard' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
ContentServer @ (index):126
close @ mui.min.js:6
r @ mui.min.js:6
(anonymous) @ mui.min.js:6
(anonymous) @ mui.min.js:6
i.each @ mui.min.js:6
(anonymous) @ mui.min.js:6
i.each @ mui.min.js:6
(anonymous) @ mui.min.js:6
(anonymous) @ mui.min.js:6
i.each @ mui.min.js:6
(anonymous) @ mui.min.js:6
i.trigger @ mui.min.js:6
e @ mui.min.js:6
(anonymous) @ mui.min.js:6
(anonymous) @ mui.min.js:6
i.each @ mui.min.js:6
i.doAction @ mui.min.js:6
m @ mui.min.js:6
z @ mui.min.js:6
(index):191 连接关闭

**Comment by liujiaqi7998** [comment]
浏览器拒绝了不安全的SSL连接
解决方案：1.关闭浏览器SSL连接校验，2.部署官签的SSL证书
具体内容请百度，此问题为浏览器问题，无法解决
