### ISSUE TITLE
与服务器断开链接

### ISSUE THREAD

**Issue by nick1987xt** [liujiaqi7998/GrasscuttersWebDashboard#6]

**Comment by liujiaqi7998** [comment]
提问请带错误信息

无法连接到服务器

检测插件是否被服务器正常加载，检查连接地址是否输入错误。

浏览器按F12打开开发者工具箱查看错误日志，普遍问题是NET::ERR_CERT_AUTHORITY_INVALID Error

解决办法（任选其一）

部署一个有效的SSL证书
切换成http
设置浏览器安全级别不校验SSL证书
将服务器的证书添加到电脑信任目录
将网页拉取到本地部署打开

**Comment by wmn1525** [comment]
我这边 发现还有一种方法 直接先https://ip,访问一下 然后信任，之后就能正常连接

**Comment by liujiaqi7998** [comment]
好的，感谢你的方法，我己经加到了解决方案中
