### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by ZXAS007** [liujiaqi7998/GrasscuttersWebDashboard#7]
1.当进入服务器后取消移动数据apn中的代理，使用/wt命令获取邮件会会提示找不到uid

2.任务一栏无法点击，打开任务一栏后会导致整个页面实现，无法点击

3.会频繁提示断开连接（并不是因为配置设置的失效时间）

4.希望可以优化一下打开分类栏卡住问题，打开分类栏/搜索时的时候会因为加载大量项目按钮卡住，需要等待几秒到十几秒响应

**Comment by liujiaqi7998** [comment]
1. 因为疫情原因没有安装手机版，不太清楚，但是大概率和你的代理有关
2. 分类栏是缓存到本地的，因为内容较多可能会卡死，我会在期末考试结束后继续修复
3. 会频繁提示断开连接在[V3.0.0](https://github.com/liujiaqi7998/GrasscuttersWebDashboard/releases/tag/V3.0.0)版本已经修复，可以尝试一下。

**Comment by ZXAS007** [comment]
1.这里使用的是Genshin Impact Proxy模块直接hook原神国际版客户端配合apn代理实现免证书的进入游戏，不清楚具体影响，可能插件的连接不是一个持久的，需要时产生，所以取消代理后会找不到uid

3.我目前使用的就是3.0

**Comment by liujiaqi7998** [comment]
是的，有可能是因为连接过程中因为某些原因造成连接中断，再次连接时密钥已经过期
