### ISSUE TITLE
运行服务器闪退

### ISSUE THREAD

**Issue by cbjcbjcbj0** [liujiaqi7998/GrasscuttersWebDashboard#8]
报错NoClassDefFoundError:emu/grasscutter/utils/messagehandler
希望有空帮忙解答  谢谢！

**Comment by liujiaqi7998** [comment]
请附带割草机版本号和插件版本号

**Comment by liujiaqi7998** [comment]
该报错可能会影响到WebTool接收操作结果，但不会影响使用和游戏，具体原因以后再排查

**Comment by cbjcbjcbj0** [comment]
插件版本号是3.0.0，割草机版本号没有找到，多谢解答
