### ISSUE TITLE
关于IOS假后台断连问题

### ISSUE THREAD

**Issue by Extrwave** [liujiaqi7998/GrasscuttersWebDashboard#9]
成员如果使用IOS手机的话，网页浏览器打开就会让游戏进入假后台，与服务器断开连接
从而导致 这个生产成的链接也会失效，考虑针对这个问题优化一下吗？
比如提供 **后台链接地址** 和 **验证码** 就可以实现浏览器手动连接等方式

**Comment by liujiaqi7998** [comment]
好的，我明白你的意思了，会对新版本做出调整来动态延长 **验证码** 的失效时间，并设计手动连接的方式。

**Comment by Extrwave** [comment]
感谢答复，期待你的新版本
